### ISSUE TITLE
大佬可不可以对jqweui进行版本升级啊,腾讯weui 都升级2了

### ISSUE THREAD

**Issue by leqq00** [lihongxun945/myblog#48]
大佬可不可以对jqweui进行版本升级啊,腾讯weui 都升级2了,能不能在升级的同时向下兼容现在的版本

**Comment by lihongxun945** [comment]
已经多年没有用过jQuery了，业界主流也早就是react/vue/angular体系，对于已经逐渐被淘汰的技术不打算继续更新了
